### ISSUE TITLE
数据包无法上传

### ISSUE THREAD

**Issue by Lucifer1993** [HatBoy/Pcap-Analyzer#17]
### 提示如下错误信息

builtins.AttributeError
AttributeError: 'FileNotFoundError' object has no attribute 'message'

Traceback (most recent call last)
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 33, in reraise
raise value
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 33, in reraise
raise value
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/root/Pcap-Analyzer/app/views.py", line 59, in upload
Open an interactive python shell in this frameflash('上传错误,错误信息:' + e.message)
AttributeError: 'FileNotFoundError' object has no attribute 'message'
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object

**Comment by HatBoy** [comment]
上传代码时上传失败，触发了view.py59行代码的错误，将59行改成这样的：flash('上传错误,错误信息:' +str(e))，然后重新上传文件看看是什么问题导致上传失败的

**Comment by HatBoy** [comment]
目测原因是没有配置上传文件保存目录

**Comment by Lucifer1993** [comment]
是的，确实是默认配置就启动服务了，上传路径找不到爆的错误，，
