### ISSUE TITLE
gunicorn启动reader.py报错SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by twosmi1e** [HatBoy/Pcap-Analyzer#37]
[2020-11-24 21:25:42 +0800] [23931] [DEBUG] Current configuration:
  preload_app: False
  reuse_port: False
  capture_output: False
  statsd_host: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-SSL': 'on', 'X-FORWARDED-PROTO': 'https'}
  syslog_prefix: None
  max_requests_jitter: 0
  pre_fork: <function Prefork.pre_fork at 0x7f306380b158>
  proxy_allow_ips: ['127.0.0.1']
  limit_request_fields: 100
  strip_header_spaces: False
  max_requests: 0
  graceful_timeout: 30
  proc_name: gunicorn.pid
  paste: None
  limit_request_line: 4094
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f306380b378>
  daemon: False
  when_ready: <function WhenReady.when_ready at 0x7f306380b048>
  pre_exec: <function PreExec.pre_exec at 0x7f306380b6a8>
  accesslog: None
  disable_redirect_access_to_syslog: False
  errorlog: -
  pidfile: /var/log/gunicorn/debug.log
  forwarded_allow_ips: ['127.0.0.1']
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  enable_stdio_inheritance: False
  config: deploy_config.py
  dogstatsd_tags:
  sendfile: None
  logger_class: gunicorn.glogging.Logger
  post_fork: <function Postfork.post_fork at 0x7f306380b268>
  pre_request: <function PreRequest.pre_request at 0x7f306380b7b8>
  spew: False
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f306380bb70>
  chdir: /root/Code/Pcap-Analyzer
  worker_tmp_dir: None
  user: 0
  group: 0
  certfile: None
  child_exit: <function ChildExit.child_exit at 0x7f306380b950>
  worker_exit: <function WorkerExit.worker_exit at 0x7f306380ba60>
  threads: 1
  limit_request_field_size: 8190
  timeout: 30
  syslog: False
  keepalive: 2
  worker_int: <function WorkerInt.worker_int at 0x7f306380b488>
  reload: False
  worker_abort: <function WorkerAbort.worker_abort at 0x7f306380b598>
  do_handshake_on_connect: False
  backlog: 2048
  ssl_version: 2
  ca_certs: None
  worker_connections: 1000
  reload_extra_files: []
  check_config: False
  worker_class: sync
  logconfig: None
  statsd_prefix:
  suppress_ragged_eofs: True
  raw_env: []
  keyfile: None
  default_proc_name: run:app
  syslog_facility: user
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  pythonpath: None
  on_exit: <function OnExit.on_exit at 0x7f306380bc80>
  raw_paste_global_conf: []
  bind: ['0.0.0.0:8000']
  cert_reqs: 0
  on_starting: <function OnStarting.on_starting at 0x7f3063cfdd90>
  on_reload: <function OnReload.on_reload at 0x7f3063cfdea0>
  post_request: <function PostRequest.post_request at 0x7f306380b840>
  workers: 1
  loglevel: debug
  proxy_protocol: False
  ciphers: None
  reload_engine: auto
[2020-11-24 21:25:42 +0800] [23931] [INFO] Starting gunicorn 20.0.4
[2020-11-24 21:25:42 +0800] [23931] [DEBUG] Arbiter booted
[2020-11-24 21:25:42 +0800] [23931] [INFO] Listening at: http://0.0.0.0:8000 (23931)
[2020-11-24 21:25:42 +0800] [23931] [INFO] Using worker: sync
[2020-11-24 21:25:42 +0800] [23934] [INFO] Booting worker with pid: 23934
[2020-11-24 21:25:42 +0800] [23931] [DEBUG] 1 workers
[2020-11-24 21:25:42 +0800] [23934] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/root/Code/Pcap-Analyzer/run.py", line 4, in <module>
    from app import app
  File "/root/Code/Pcap-Analyzer/app/__init__.py", line 11, in <module>
    from app import views
  File "/root/Code/Pcap-Analyzer/app/views.py", line 12, in <module>
    from .utils.ipmap_tools import getmyip, get_ipmap, get_geo
  File "/root/Code/Pcap-Analyzer/app/utils/ipmap_tools.py", line 7, in <module>
    import geoip2.database
  File "/usr/local/lib/python3.5/dist-packages/geoip2/database.py", line 9, in <module>
    import maxminddb
  File "/usr/local/lib/python3.5/dist-packages/maxminddb/__init__.py", line 5, in <module>
    import maxminddb.reader
  File "/usr/local/lib/python3.5/dist-packages/maxminddb/reader.py", line 36
    _buffer: Union[bytes, FileBuffer, "mmap.mmap"]
           ^
SyntaxError: invalid syntax
[2020-11-24 21:25:42 +0800] [23934] [INFO] Worker exiting (pid: 23934)
[2020-11-24 21:25:42 +0800] [23931] [INFO] Shutting down: Master
[2020-11-24 21:25:42 +0800] [23931] [INFO] Reason: Worker failed to boot.

**Comment by twosmi1e** [comment]
已解决
https://stackoverflow.com/questions/63846046/python-geoip2-maxminddb-reader-error-in-ec2-server
Its working after I changed the geoip2==2.9.0 maxminddb==1.4.1
